# Generated by Django 4.2 on 2025-10-29 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notificationrecipient',
            name='deliveredAt',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
